/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Buffer messages in seconds to avoid system overload": {"en": "Buffer messages in seconds to avoid system overload", "de": "Puffern Sie Nachrichten in Sekundenschnelle, um eine Systemüberlastung zu vermeiden", "ru": "Буферизация сообщений за считанные секунды, чтобы избежать перегрузки системы.", "pt": "Mensagens de buffer em segundos para evitar sobrecarga do sistema", "nl": "Buffer berichten binnen enkele seconden om systeemoverbelasting te voorkomen", "fr": "Tamponnez les messages en quelques secondes pour éviter la surcharge du système", "it": "Buffer dei messaggi in pochi secondi per evitare il sovraccarico del sistema", "es": "Almacene los mensajes en segundos para evitar la sobrecarga del sistema", "pl": "Buforuj wiadomości w ciągu kilku sekund, aby uniknąć przeciążenia systemu", "zh-cn": "在几秒钟内缓冲消息以避免系统过载"},
    "Leave empty or 0 to not expire states": {       "en": "Leave empty or 0 to not expire states",           "de": "Leer lassen oder 0, um den Status nicht abzulaufen", "ru": "Оставьте пустым или 0, чтобы состояния не истекали.", "pt": "Deixe em branco ou 0 para não expirar os estados", "nl": "Laat leeg of 0 om de status niet te laten verlopen", "fr": "Laissez vide ou 0 pour ne pas expirer les états", "it": "Lascia vuoto o 0 per non far scadere gli stati",  "es": "Déjelo vacío o 0 para que no caduquen los estados", "pl": "Pozostaw puste lub 0, aby stany nie wygasały",    "zh-cn": "留空或 0 表示不过期状态"},
    "Please choose your preferred settings": {       "en": "Please choose your preferred settings",           "de": "Bitte wählen Sie Ihre bevorzugten Einstellungen", "ru": "Пожалуйста, выберите предпочитаемые настройки",   "pt": "Escolha suas configurações preferidas",           "nl": "Kies uw voorkeursinstellingen",                   "fr": "Veuillez choisir vos paramètres préférés",        "it": "Scegli le impostazioni preferite",                "es": "Por favor elige tu configuración preferida",      "pl": "Wybierz preferowane ustawienia",                  "zh-cn": "请选择您喜欢的设置"},
    "USBDevice": {                                   "en": "USB device Port",                                 "de": "USB-Geräteanschluss",                             "ru": "Порт USB-устройства",                             "pt": "Porta do dispositivo USB",                        "nl": "USB-apparaatpoort",                               "fr": "Port de périphérique USB",                        "it": "Porta del dispositivo USB",                       "es": "Puerto del dispositivo USB",                      "pl": "Port urządzenia USB",                             "zh-cn": "USB设备端口"},
    "expireTime": {                                  "en": "Expiration time of states in seconds",            "de": "Ablaufzeit der Zustände in Sekunden",             "ru": "Время истечения состояний в секундах",            "pt": "Tempo de expiração dos estados em segundos",      "nl": "Vervaltijd van staten in seconden",               "fr": "Temps d'expiration des états en secondes",        "it": "Tempo di scadenza degli stati in secondi",        "es": "Tiempo de vencimiento de los estados en segundos.", "pl": "Czas ważności stanów w sekundach",                "zh-cn": "状态的过期时间（以秒为单位）"},
    "messageBuffer": {                               "en": "Buffer in seconds to ignore messages",            "de": "Puffer in Sekunden, um Nachrichten zu ignorieren", "ru": "Буфер в секундах для игнорирования сообщений",    "pt": "Buffer em segundos para ignorar mensagens",       "nl": "Buffer in seconden om berichten te negeren",      "fr": "Tampon en quelques secondes pour ignorer les messages", "it": "Buffer in pochi secondi per ignorare i messaggi", "es": "Buffer en segundos para ignorar mensajes",        "pl": "Bufor w ciągu kilku sekund, aby ignorować wiadomości", "zh-cn": "以秒为单位进行缓冲以忽略消息"},
};